### ISSUE TITLE
Module serving the dblog entries

### ISSUE THREAD

**Issue by dawehner** [mattgrill/drupal-react-dblog#1]
Do you mind also providing the module which returns the Dblog data itself?

**Comment by mattgrill** [comment]
@dawehner I just included the views export, https://github.com/mattgrill/drupal-react-dblog/blob/master/view.yml

**Comment by dawehner** [comment]
Oh, I did not expected that this is powered by views :)

**Comment by mattgrill** [comment]
@dawehner Yep. Easiest bit of effort so far.

**Comment by dawehner** [comment]
Let's close ir
