### ISSUE TITLE
Multi select list behavior

### ISSUE THREAD

**Issue by tesliker** [mattgrill/drupal-react-dblog#9]
The Multi select list has a few issues that I would not expect. When I choose a second item, it keeps the old selection as well without me holding the command or ctrl key. Also, after I select an item, I cannot unselect it if it is the last one left. This might be a "feature", but it is confusing to me.

**Comment by tesliker** [comment]
I can see the usefulness of the first feature where clicking just adds to the list, but I think users should be able to unselect the only selected item. The reason this immediately came up is because I select an item and all dblog errors disappeared, so I wanted to go back and see what kind of errors I have.

**Comment by tesliker** [comment]
Easy fix for me was changing the changeHandler function of the select component to run onClick

**Comment by tesliker** [comment]
This was addressed in PR #11, Select lists now function normally.

**Comment by dawehner** [comment]
@tommy sliker
Thank you for closing!
